// src/localization/arabic_localization.js

export const arabicLocalization = {
  // ==================== NAVIGATION ====================
  "home": "الرئيسية",
  "poems": "قصائد",
  "prose": "نثر",
  "poets": "شعراء",
  "contributors": "المساهمون",
  "about": "عن الموقع",
  "testPage": "صفحة اختبار",
  
  // Poems Dropdown
  "allPoems": "جميع القصائد",
  "popular": "الأكثر شعبية",
  "new": "جديد",
  "classics": "كلاسيكيات",
  "categories": "الفئات",
  "poemTypes": "أنواع القصائد",
  
  // Prose Dropdown
  "allProse": "جميع النثر",
  "shortStories": "قصص قصيرة",
  "essays": "مقالات",
  "articles": "مقاالت",
  "memoirs": "مذكرات",
  "literaryCriticism": "نقد أدبي",
  
  // Poets Dropdown
  "allPoets": "جميع الشعراء",
  "featured": "مميز",
  "newPoets": "شعراء جدد",
  "interviews": "مقابلات",
  
  // Contributors Dropdown
  "allContributors": "جميع المساهمين",
  "translators": "مترجمون",
  "scholars": "علماء",
  "editors": "محررون",
  "commentators": "معلقون",

  // UI Elements
  "search": "ابحث عن قصائد، شعراء...",
  "signUp": "اشتراك",
  "login": "تسجيل الدخول",
  "profile": "الملف الشخصي",
  "settings": "الإعدادات",
  "notifications": "الإشعارات",
  "theme": "المظهر",
  "language": "اللغة",
  "aiAssistant": "مساعد الذكاء الاصطناعي",
  "menu": "القائمة",
  "viewAll": "عرض الكل",
  "explore": "استكشاف",
  "read": "قراءة",
  "filter": "تصفية",
  "type": "النوع",
  "allTypes": "جميع الأنواع",
  "allLanguages": "جميع اللغات",
  "sortBy": "ترتيب حسب",
  "newest": "الأحدث",
  "oldest": "الأقدم",
  "mostLiked": "الأكثر إعجاباً",
  "mostViewed": "الأكثر مشاهدة",
  "showing": "عرض",
  "readMore": "اقرأ المزيد",
  "by": "بواسطة",
  "likes": "إعجابات",
  "of": "من",
  "noPoemsFound": "لم يتم العثور على قصائد",
  "tryDifferentSearch": "حاول تعديل بحثك أو عوامل التصفية",
  "dashboard": "لوحة التحكم",
  "logout": "تسجيل الخروج",
  "exploreNow": "استكشف الآن",

  // ==================== FOOTER ====================
  "brandDescription": "ملاذ للشعر والنثر والتعبير الأدبي. اكتشف أعمالاً من أصوات متنوعة عبر اللغات والثقافات.",
  "quickLinks": "روابط سريعة",
  "resources": "الموارد",
  "getInTouch": "تواصل معنا",
  "subscribe": "اشترك",
  "yourEmail": "بريدك الإلكتروني",
  "subscribeBtn": "اشترك",
  "allRightsReserved": "جميع الحقوق محفوظة",
  "privacy": "الخصوصية",
  "terms": "الشروط",
  "sitemap": "خريطة الموقع",
  "madeWith": "صنع بـ",
  "for": "لـ",
  "poetryLovers": "عشاق الشعر",
  "backToTop": "العودة للأعلى",
  "writingTips": "نصائح للكتابة",
  "poetryGlossary": "معجم الشعر",
  "famousPoets": "شعراء مشهورون",
  "contests": "مسابقات",
  "workshops": "ورش عمل",
  "poetryForms": "أشكال الشعر",

  // ==================== HOMEPAGE ====================
  "welcome": "مرحباً بكم في",
  "exploreLiteraryWorlds": "استكشف العوالم الأدبية",
  "featuredPoems": "قصائد مميزة",
  "meetPoets": "تعرف على الشعراء",
  "joinCommunity": "انضم إلى مجتمعنا",
  "explorePoems": "استكشف القصائد",
  "learnMore": "اعرف المزيد",
  "heroTitle": "ملاذ للشعر والنثر والتعبير الأدبي",
  "heroSubtitle": "اكتشف أعمالاً من أصوات متنوعة عبر اللغات والثقافات.",
  "readers": "قراء",
  "works": "أعمال",
  "footerNote": "صنع بـ ❤️ لعشاق الشعر والأدب حول العالم",

  // ==================== POEMS PAGE ====================
  "poemsDescription": "اكتشف قصائد من جميع أنحاء العالم",
  "searchPoems": "ابحث عن قصائد، شعراء...",
  "noPoemsFound": "لم يتم العثور على قصائد",

  // ==================== PROSE PAGE ====================
  "proseDescription": "استكشف المقالات، القصص القصيرة، المذكرات والمزيد",
  "searchProse": "ابحث عن نثر، مؤلفين...",
  "category": "الفئة",
  "allCategories": "جميع الفئات",
  "noProseFound": "لم يتم العثور على نثر",
  "proseItems": "عناصر النثر",

  // ==================== POETS PAGE ====================
  "poetsDescription": "اكتشف شعراء من جميع أنحاء العالم واستكشف أعمالهم",
  "searchPoets": "ابحث عن شعراء بالاسم، البلد أو الأسلوب...",
  "country": "الدولة",
  "allCountries": "جميع الدول",
  "era": "الحقبة",
  "allEras": "جميع الحقب",
  "mostPopular": "الأكثر شعبية",
  "mostFollowers": "الأكثر متابعة",
  "mostWorks": "الأكثر أعمالاً",
  "noPoetsFound": "لم يتم العثور على شعراء",
  "allRoles": "جميع الأدوار",

  // ==================== CONTRIBUTORS PAGE ====================
  "contributorsDescription": "تعرف على العلماء والمترجمين والمحررين والمعلقين الذين يثريون مجتمعنا الأدبي",
  "searchContributors": "ابحث بالاسم، الدور أو التخصص...",
  "role": "الدور",
  "noContributorsFound": "لم يتم العثور على مساهمين",

  // ==================== ABOUT PAGE ====================
  "aboutTitle": "عن الموقع",
  "aboutSubtitle": "ملاذ للشعر والنثر والتعبير الأدبي",
  "ourMission": "مهمتنا",
  "ourVision": "رؤيتنا",
  "ourValues": "قيمنا",
  "ourImpact": "تأثيرنا",
  "ourTeam": "فريقنا",
  "joinUs": "انضم إلى مجتمعنا",
  "joinUsDesc": "سواء كنت شاعراً، كاتباً أو متحمساً للأدب، هناك مكان لك في براسانغ.",
  "contactUs": "اتصل بنا",

  // ==================== TESTIMONIALS ====================
  "whatReadersSay": "ماذا يقول قراؤنا",
  "testimonialsDesc": "استمع إلى مجتمعنا من القراء والكتاب وعشاق الأدب",

  // ==================== NEWSLETTER ====================
  "subscribeNewsletter": "اشترك في نشرتنا الإخبارية",
  "newsletterDesc": "احصل على أحدث القصائد والنثر والأخبار الأدبية في بريدك الوارد",
  "yourName": "اسمك (اختياري)",
  "enterName": "أدخل اسمك",
  "emailAddress": "البريد الإلكتروني",
  "enterEmail": "أدخل بريدك الإلكتروني",
  "emailRequired": "يرجى إدخال بريدك الإلكتروني",
  "invalidEmail": "يرجى إدخال بريد إلكتروني صحيح",
  "subscribing": "جاري الاشتراك...",
  "subscribedSuccess": "لقد اشتركت! 🎉",
  "subscribedDesc": "شكراً للاشتراك. تحقق من بريدك الوارد للتأكيد.",
  "noSpam": "لا بريد مزعج. يمكنك إلغاء الاشتراك في أي وقت.",
  "subscriptionError": "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
  "weeklyPoems": "قصائد مختارة أسبوعياً",
  "exclusiveContent": "محتوى حصري من شعراء مميزين",
  "eventUpdates": "تحديثات الفعاليات والمسابقات",

  // ==================== CTA SECTION ====================
  "ctaBadge": "انضم إلى المجتمع",
  "ctaTitle": "هل أنت مستعد لبدء رحلتك الأدبية؟",
  "ctaDescription": "انضم إلى آلاف الشعراء والكتاب وعشاق الأدب الذين هم بالفعل جزء من مجتمعنا المتنامي.",
  "ctaJoinNow": "انضم الآن مجاناً",
  "ctaJoinDesc": "أنشئ حسابك وابدأ الاستكشاف اليوم.",
  "members": "أعضاء",
  "trustLoved": "محبوب من القراء",
  "trustLovedDesc": "آلاف من عشاق الشعر",
  "trustCurated": "محتوى منسق",
  "trustCuratedDesc": "منتقي بعناية من قبل الخبراء",
  "trustCommunity": "مجتمع نشط",
  "trustCommunityDesc": "تواصل مع القراء الآخرين",
  "trustGlobal": "وصول عالمي",
  "trustGlobalDesc": "قراء من أكثر من 100 دولة",

  // ==================== LITERARY CATEGORIES ====================
  "literaryCategories": "الفئات الأدبية",
  "categoriesDesc": "استكشف مختلف الأنواع والأشكال الأدبية من جميع أنحاء العالم",
  "viewAllCategories": "عرض جميع الفئات",

  // ==================== TEST PAGE ====================
  "testPageDescription": "اختبار مكونات واجهة المستخدم والمظاهر والتفاعلات",
  "buttons": "أزرار",
  "clickMe": "اضغطني",
  "error": "خطأ",
  "warning": "تحذير",
  "info": "معلومات",
  "simulateLoading": "محاكاة التحميل",
  "loading": "جاري التحميل...",
  "buttonClicks": "نقرات الأزرار",
  "formElements": "عناصر النموذج",
  "textInput": "إدخال نصي",
  "typeSomething": "اكتب شيئاً...",
  "inputValue": "قيمة الإدخال",
  "toggleMe": "تبديل",
  "dropdown": "قائمة منسدلة",
  "option1": "خيار 1",
  "option2": "خيار 2",
  "option3": "خيار 3",
  "selected": "محدد",
  "rangeSlider": "شريط التمرير",
  "iconShowcase": "عرض الأيقونات",
  "tabs": "علامات تبويب",
  "progressBar": "شريط التقدم",
  "colorPalette": "لوحة الألوان",
  "testPageFooter": "هذه صفحة اختبار لمكونات واجهة المستخدم والتفاعلات",

  // ==================== CONTROLS ====================
  "controls": "التحكم",
  "controlsPreferences": "التحكم والتفضيلات",
  "literature": "الأدب",
  "aiTranslation": "ترجمة الذكاء الاصطناعي",
  "defaultTheme": "العنبر الافتراضي",
  "forestTheme": "الغابة الخضراء",
  "lavenderTheme": "اللافندر البنفسجي",
  "roseTheme": "الوردي",
  "sepiaTheme": "البني القديم",
  "darkTheme": "الوضع المظلم",
  "quickSettings": "إعدادات سريعة",
  "fullPreferences": "التفضيلات الكاملة",
  "preferencesSaved": "تم حفظ التفضيلات محلياً",
  "close": "إغلاق",
  "enableRealTimeTranslation": "تفعيل الترجمة الفورية",
  "audioPlayback": "تشغيل الصوت",
  "readPoemsAloud": "قراءة القصائد بصوت عال",
  "toggleAiTranslation": "تبديل ترجمة الذكاء الاصطناعي",
  "toggleAudio": "تبديل الصوت",
  "selectUpTo3Languages": "حدد حتى 3 لغات",
  "selectLiteratureLanguage": "اختر لغة الأدب",
  "searchLanguages": "ابحث عن لغات...",
  "showMore": "عرض المزيد",
  "showLess": "عرض أقل",
  "more": "المزيد",
  "languagesAvailable": "لغات متاحة",
  "select": "اختر",
  "romanzation": "الكتابة بالحروف اللاتينية",
  "convertScriptToLatin": "تحويل النص إلى حروف لاتينية",
  "enablesTransliteration": "تمكين الترجمة الصوتية لتحسين القراءة",
  "toggleRomanization": "تبديل الكتابة بالحروف اللاتينية",
  "maxLanguagesReached": "تم اختيار الحد الأقصى 3 لغات",

  // ==================== GENERAL ====================
  "toggleDropdown": "تبديل القائمة المنسدلة",
  "noNavItems": "لم يتم تحميل عناصر التنقل",
  "openMenu": "فتح القائمة",
  "closeMenu": "إغلاق القائمة",
};

// ✅ Default export for backwards compatibility
export default arabicLocalization;