// src/localization/english_localization.js

export const englishLocalization = {
  // ==================== NAVIGATION ====================
  // Main Navigation
  "home": "Home",
  "poems": "Poems",
  "prose": "Prose",
  "poets": "Poets",
  "contributors": "Contributors",
  "about": "About",
  "testPage": "Test Page",
  
  // Poems Dropdown
  "allPoems": "All Poems",
  "popular": "Popular",
  "new": "New",
  "classics": "Classics",
  "categories": "Categories",
  "poemTypes": "Poem Types",
  
  // Prose Dropdown
  "allProse": "All Prose",
  "shortStories": "Short Stories",
  "essays": "Essays",
  "articles": "Articles",
  "memoirs": "Memoirs",
  "literaryCriticism": "Literary Criticism",
  
  // Poets Dropdown
  "allPoets": "All Poets",
  "featured": "Featured",
  "newPoets": "New Poets",
  "interviews": "Interviews",
  
  // Contributors Dropdown
  "allContributors": "All Contributors",
  "translators": "Translators",
  "scholars": "Scholars",
  "editors": "Editors",
  "commentators": "Commentators",

  // UI Elements
  "search": "Search poems, poets...",
  "signUp": "Sign Up",
  "login": "Login",
  "profile": "Profile",
  "settings": "Settings",
  "notifications": "Notifications",
  "theme": "Theme",
  "language": "Language",
  "aiAssistant": "AI Assistant",
  "aiTools": "AI Tools",
  "poemGenerator": "Poem Generator",
  "rhymeFinder": "Rhyme Finder",
  "meterAnalyzer": "Meter Analyzer",
  "translationAssistant": "Translation Assistant",
  "writingPrompts": "Writing Prompts",
  "account": "Account",
  "menu": "Menu",

  // ==================== FOOTER ====================
  "brandDescription": "A sanctuary for poetry, prose, and literary expression. Discover works from diverse voices across languages and cultures.",
  "quickLinks": "Quick Links",
  "resources": "Resources",
  "getInTouch": "Get In Touch",
  "subscribe": "Subscribe",
  "yourEmail": "Your email",
  "subscribeBtn": "Subscribe",
  "allRightsReserved": "All rights reserved",
  "privacy": "Privacy",
  "terms": "Terms",
  "sitemap": "Sitemap",
  "madeWith": "Made with",
  "for": "for",
  "poetryLovers": "Poetry Lovers",
  "backToTop": "Back to Top",

  // Footer Resources
  "writingTips": "Writing Tips",
  "poetryGlossary": "Poetry Glossary",
  "famousPoets": "Famous Poets",
  "contests": "Contests",
  "workshops": "Workshops",
  "poetryForms": "Poetry Forms",

  // ==================== HERO SLIDER ====================
  "featured": "Featured",
  "explorePoems": "Explore Poems",
  "learnMore": "Learn More",
  "welcome": "Welcome to",
  "exploreLiteraryWorlds": "Explore Literary Worlds",
  "featuredPoems": "Featured Poems",
  "meetPoets": "Meet the Poets",
  "joinCommunity": "Join Our Community",
  "read": "Read",

  // ==================== HOMEPAGE ====================
  // Hero Section
  "heroTitle": "A sanctuary for poetry, prose, and literary expression",
  "heroSubtitle": "Discover works from diverse voices across languages and cultures.",
  "heroCta": "Explore Poems",
  "heroCta2": "Learn More",

  // Featured Poems
  "featuredPoemsDesc": "Discover handpicked poems from renowned and emerging poets.",
  "featuredPoetsDesc": "Explore the lives and works of poets from around the world.",
  "literaryCriticismDesc": "Dive deep into analysis and interpretation of classic works.",
  "exploreNow": "Explore Now",
  "viewAll": "View All",

  // Stats
  "readers": "Readers",
  "works": "works",
  "by": "By",
  "likes": "likes",
  "of": "of",

  // ==================== POEMS PAGE ====================
  "poemsDescription": "Discover poems from around the world",
  "searchPoems": "Search poems, poets...",
  "filter": "Filter",
  "type": "Type",
  "allTypes": "All Types",
  "allLanguages": "All Languages",
  "sortBy": "Sort By",
  "newest": "Newest",
  "oldest": "Oldest",
  "mostLiked": "Most Liked",
  "mostViewed": "Most Viewed",
  "noPoemsFound": "No poems found",
  "tryDifferentSearch": "Try adjusting your search or filters",
  "showing": "Showing",
  "readMore": "Read More",

  // ==================== PROSE PAGE ====================
  "proseDescription": "Explore essays, short stories, memoirs, and more",
  "searchProse": "Search prose, authors...",
  "category": "Category",
  "allCategories": "All Categories",
  "noProseFound": "No prose found",
  "proseItems": "prose items",

  // ==================== POETS PAGE ====================
  "poetsDescription": "Discover poets from around the world and explore their works",
  "searchPoets": "Search poets by name, country, or style...",
  "country": "Country",
  "allCountries": "All Countries",
  "era": "Era",
  "allEras": "All Eras",
  "mostPopular": "Most Popular",
  "mostFollowers": "Most Followers",
  "mostWorks": "Most Works",
  "noPoetsFound": "No poets found",
  "allRoles": "All Roles",

  // ==================== CONTRIBUTORS PAGE ====================
  "contributorsDescription": "Meet the scholars, translators, editors, and commentators who enrich our literary community",
  "searchContributors": "Search by name, role, or specialty...",
  "role": "Role",
  "noContributorsFound": "No contributors found",

  // ==================== ABOUT PAGE ====================
  "aboutTitle": "About Us",
  "aboutSubtitle": "A sanctuary for poetry, prose, and literary expression",
  "ourMission": "Our Mission",
  "ourVision": "Our Vision",
  "ourValues": "Our Values",
  "ourImpact": "Our Impact",
  "ourTeam": "Our Team",
  "joinUs": "Join Our Community",
  "joinUsDesc": "Whether you're a poet, writer, or literature enthusiast, there's a place for you at Prasang.",
  "contactUs": "Contact Us",

  // ==================== TESTIMONIALS ====================
  "whatReadersSay": "What Our Readers Say",
  "testimonialsDesc": "Hear from our community of readers, writers, and literature enthusiasts",

  // ==================== NEWSLETTER ====================
  "subscribeNewsletter": "Subscribe to Our Newsletter",
  "newsletterDesc": "Get the latest poems, prose, and literary news delivered to your inbox",
  "yourName": "Your Name (Optional)",
  "enterName": "Enter your name",
  "emailAddress": "Email Address",
  "enterEmail": "Enter your email",
  "emailRequired": "Please enter your email",
  "invalidEmail": "Please enter a valid email address",
  "subscribing": "Subscribing...",
  "subscribedSuccess": "You're Subscribed! 🎉",
  "subscribedDesc": "Thank you for subscribing. Check your inbox for confirmation.",
  "noSpam": "No spam. Unsubscribe anytime.",
  "subscriptionError": "Something went wrong. Please try again.",
  "weeklyPoems": "Weekly curated poems",
  "exclusiveContent": "Exclusive content from featured poets",
  "eventUpdates": "Event and contest updates",

  // ==================== CTA SECTION ====================
  "ctaBadge": "Join the Community",
  "ctaTitle": "Ready to Begin Your Literary Journey?",
  "ctaDescription": "Join thousands of poets, writers, and literature lovers who are already part of our growing community.",
  "ctaJoinNow": "Join Now for Free",
  "ctaJoinDesc": "Create your account and start exploring today.",
  "members": "Members",
  "trustLoved": "Loved by Readers",
  "trustLovedDesc": "Thousands of poetry lovers",
  "trustCurated": "Curated Content",
  "trustCuratedDesc": "Handpicked by experts",
  "trustCommunity": "Active Community",
  "trustCommunityDesc": "Connect with fellow readers",
  "trustGlobal": "Global Reach",
  "trustGlobalDesc": "Readers from 100+ countries",

  // ==================== LITERARY CATEGORIES ====================
  "literaryCategories": "Literary Categories",
  "categoriesDesc": "Explore different genres and forms of literature from around the world",
  "viewAllCategories": "View All Categories",

  // ==================== TEST PAGE ====================
  "testPageDescription": "Testing UI components, themes, and interactions",
  "buttons": "Buttons",
  "clickMe": "Click Me",
  "error": "Error",
  "warning": "Warning",
  "info": "Info",
  "simulateLoading": "Simulate Loading",
  "loading": "Loading...",
  "buttonClicks": "Button clicks",
  "formElements": "Form Elements",
  "textInput": "Text Input",
  "typeSomething": "Type something...",
  "inputValue": "Input value",
  "toggleMe": "Toggle Me",
  "dropdown": "Dropdown",
  "option1": "Option 1",
  "option2": "Option 2",
  "option3": "Option 3",
  "selected": "Selected",
  "rangeSlider": "Range Slider",
  "iconShowcase": "Icon Showcase",
  "tabs": "Tabs",
  "progressBar": "Progress Bar",
  "colorPalette": "Color Palette",
  "testPageFooter": "This is a test page for UI components and interactions",

  // ==================== CONTROLS ====================
  "controls": "Controls",
  "controlsPreferences": "Controls & Preferences",
  "literature": "Literature",
  "aiTranslation": "AI Translation",
  "defaultTheme": "Default Amber",
  "forestTheme": "Forest Green",
  "lavenderTheme": "Lavender Purple",
  "roseTheme": "Rose Pink",
  "sepiaTheme": "Sepia Vintage",
  "darkTheme": "Dark Mode",
  "quickSettings": "Quick settings",
  "fullPreferences": "Full Preferences",
  "preferencesSaved": "Preferences saved locally",
  "close": "Close",
  "enableRealTimeTranslation": "Enable real-time translation",
  "audioPlayback": "Audio Playback",
  "readPoemsAloud": "Read poems aloud",
  "toggleAiTranslation": "Toggle AI Translation",
  "toggleAudio": "Toggle Audio",
  "selectUpTo3Languages": "Select up to 3 languages",
  "selectLiteratureLanguage": "Select Literature Language",
  "searchLanguages": "Search languages...",
  "showMore": "Show More",
  "showLess": "Show Less",
  "more": "more",
  "languagesAvailable": "languages available",
  "select": "Select",
  "romanzation": "Romanization",
  "convertScriptToLatin": "Convert script to Latin characters",
  "enablesTransliteration": "Enables transliteration for better readability",
  "toggleRomanization": "Toggle romanization",
  "maxLanguagesReached": "Maximum 3 languages selected",

  // ==================== GENERAL ====================
  "dashboard": "Dashboard",
  "logout": "Logout",
  "toggleDropdown": "Toggle dropdown",
  "noNavItems": "No navigation items loaded",
  "openMenu": "Open menu",
  "closeMenu": "Close menu",
  "explore": "Explore",
  "footerNote": "Made with ❤️ for poetry and literature lovers around the world",
};