// src/localization/hindi_localization.js

export const hindiLocalization = {
  // ==================== NAVIGATION ====================
  // Main Navigation
  "home": "होम",
  "poems": "कविताएँ",
  "prose": "गद्य",
  "poets": "कवि",
  "contributors": "योगदानकर्ता",
  "about": "हमारे बारे में",
  "testPage": "टेस्ट पेज",
  
  // Poems Dropdown
  "allPoems": "सभी कविताएँ",
  "popular": "लोकप्रिय",
  "new": "नई",
  "classics": "क्लासिक्स",
  "categories": "श्रेणियाँ",
  "poemTypes": "कविता के प्रकार",
  
  // Prose Dropdown
  "allProse": "सभी गद्य",
  "shortStories": "लघु कथाएँ",
  "essays": "निबंध",
  "articles": "लेख",
  "memoirs": "संस्मरण",
  "literaryCriticism": "साहित्यिक आलोचना",
  
  // Poets Dropdown
  "allPoets": "सभी कवि",
  "featured": "विशेष",
  "newPoets": "नए कवि",
  "interviews": "साक्षात्कार",
  
  // Contributors Dropdown
  "allContributors": "सभी योगदानकर्ता",
  "translators": "अनुवादक",
  "scholars": "विद्वान",
  "editors": "संपादक",
  "commentators": "टीकाकार",

  // UI Elements
  "search": "कविताएँ, कवि खोजें...",
  "signUp": "साइन अप",
  "login": "लॉग इन",
  "profile": "प्रोफ़ाइल",
  "settings": "सेटिंग्स",
  "notifications": "सूचनाएँ",
  "theme": "थीम",
  "language": "भाषा",
  "aiAssistant": "एआई सहायक",
  "aiTools": "एआई उपकरण",
  "poemGenerator": "कविता जनरेटर",
  "rhymeFinder": "तुक खोजक",
  "meterAnalyzer": "छंद विश्लेषक",
  "translationAssistant": "अनुवाद सहायक",
  "writingPrompts": "लेखन संकेत",
  "account": "खाता",
  "menu": "मेनू",

  // ==================== FOOTER ====================
  "brandDescription": "कविता, गद्य और साहित्यिक अभिव्यक्ति का अभयारण्य। विभिन्न भाषाओं और संस्कृतियों से विविध आवाज़ों की खोज करें।",
  "quickLinks": "त्वरित लिंक",
  "resources": "संसाधन",
  "getInTouch": "संपर्क करें",
  "subscribe": "सदस्यता लें",
  "yourEmail": "आपका ईमेल",
  "subscribeBtn": "सदस्यता लें",
  "allRightsReserved": "सभी अधिकार सुरक्षित",
  "privacy": "गोपनीयता",
  "terms": "नियम",
  "sitemap": "साइटमैप",
  "madeWith": "के साथ बनाया गया",
  "for": "के लिए",
  "poetryLovers": "कविता प्रेमी",
  "backToTop": "ऊपर जाएं",

  // Footer Resources
  "writingTips": "लेखन युक्तियाँ",
  "poetryGlossary": "कविता शब्दकोश",
  "famousPoets": "प्रसिद्ध कवि",
  "contests": "प्रतियोगिताएँ",
  "workshops": "कार्यशालाएँ",
  "poetryForms": "कविता के रूप",

  // ==================== HERO SLIDER ====================
  "featured": "विशेष",
  "explorePoems": "कविताएँ खोजें",
  "learnMore": "और जानें",
  "welcome": "प्रसंग में आपका स्वागत है",
  "exploreLiteraryWorlds": "साहित्यिक दुनिया का अन्वेषण करें",
  "featuredPoems": "विशेष कविताएँ",
  "meetPoets": "कवियों से मिलें",
  "joinCommunity": "हमारे समुदाय से जुड़ें",
  "read": "पढ़ें",

  // ==================== HOMEPAGE ====================
  // Hero Section
  "heroTitle": "कविता, गद्य और साहित्यिक अभिव्यक्ति का अभयारण्य",
  "heroSubtitle": "विभिन्न भाषाओं और संस्कृतियों से विविध आवाज़ों की खोज करें।",
  "heroCta": "कविताएँ खोजें",
  "heroCta2": "और जानें",

  // Featured Poems
  "featuredPoemsDesc": "प्रसिद्ध और उभरते कवियों की हाथ से चुनी गई कविताओं की खोज करें।",
  "featuredPoetsDesc": "दुनिया भर के कवियों के जीवन और कार्यों का अन्वेषण करें।",
  "literaryCriticismDesc": "क्लासिक कार्यों के विश्लेषण और व्याख्या में गहराई से उतरें।",
  "exploreNow": "अभी खोजें",
  "viewAll": "सभी देखें",

  // Stats
  "readers": "पाठक",
  "works": "रचनाएँ",
  "by": "द्वारा",
  "likes": "पसंद",
  "of": "में से",

  // ==================== POEMS PAGE ====================
  "poemsDescription": "दुनिया भर से कविताओं की खोज करें",
  "searchPoems": "कविताएँ, कवि खोजें...",
  "filter": "फ़िल्टर",
  "type": "प्रकार",
  "allTypes": "सभी प्रकार",
  "allLanguages": "सभी भाषाएँ",
  "sortBy": "क्रमबद्ध करें",
  "newest": "नवीनतम",
  "oldest": "सबसे पुराना",
  "mostLiked": "सबसे अधिक पसंद",
  "mostViewed": "सबसे अधिक देखा गया",
  "noPoemsFound": "कोई कविता नहीं मिली",
  "tryDifferentSearch": "अपनी खोज या फ़िल्टर समायोजित करने का प्रयास करें",
  "showing": "दिखा रहे हैं",
  "readMore": "और पढ़ें",

  // ==================== PROSE PAGE ====================
  "proseDescription": "निबंध, लघु कथाएँ, संस्मरण और बहुत कुछ खोजें",
  "searchProse": "गद्य, लेखक खोजें...",
  "category": "श्रेणी",
  "allCategories": "सभी श्रेणियाँ",
  "noProseFound": "कोई गद्य नहीं मिला",
  "proseItems": "गद्य आइटम",

  // ==================== POETS PAGE ====================
  "poetsDescription": "दुनिया भर के कवियों को खोजें और उनकी रचनाओं का अन्वेषण करें",
  "searchPoets": "नाम, देश या शैली से कवियों को खोजें...",
  "country": "देश",
  "allCountries": "सभी देश",
  "era": "युग",
  "allEras": "सभी युग",
  "mostPopular": "सबसे लोकप्रिय",
  "mostFollowers": "सबसे अधिक अनुयायी",
  "mostWorks": "सबसे अधिक रचनाएँ",
  "noPoetsFound": "कोई कवि नहीं मिला",
  "allRoles": "सभी भूमिकाएँ",

  // ==================== CONTRIBUTORS PAGE ====================
  "contributorsDescription": "उन विद्वानों, अनुवादकों, संपादकों और टीकाकारों से मिलें जो हमारे साहित्यिक समुदाय को समृद्ध करते हैं",
  "searchContributors": "नाम, भूमिका या विशेषता से खोजें...",
  "role": "भूमिका",
  "noContributorsFound": "कोई योगदानकर्ता नहीं मिला",

  // ==================== ABOUT PAGE ====================
  "aboutTitle": "हमारे बारे में",
  "aboutSubtitle": "कविता, गद्य और साहित्यिक अभिव्यक्ति का अभयारण्य",
  "ourMission": "हमारा मिशन",
  "ourVision": "हमारा दृष्टिकोण",
  "ourValues": "हमारे मूल्य",
  "ourImpact": "हमारा प्रभाव",
  "ourTeam": "हमारी टीम",
  "joinUs": "हमारे समुदाय से जुड़ें",
  "joinUsDesc": "चाहे आप कवि हों, लेखक हों या साहित्य प्रेमी, प्रसंग में आपके लिए एक जगह है।",
  "contactUs": "संपर्क करें",

  // ==================== TESTIMONIALS ====================
  "whatReadersSay": "हमारे पाठक क्या कहते हैं",
  "testimonialsDesc": "हमारे पाठकों, लेखकों और साहित्य प्रेमियों के समुदाय से सुनें",

  // ==================== NEWSLETTER ====================
  "subscribeNewsletter": "हमारे न्यूज़लेटर की सदस्यता लें",
  "newsletterDesc": "नवीनतम कविताएँ, गद्य और साहित्यिक समाचार अपने इनबॉक्स में प्राप्त करें",
  "yourName": "आपका नाम (वैकल्पिक)",
  "enterName": "अपना नाम दर्ज करें",
  "emailAddress": "ईमेल पता",
  "enterEmail": "अपना ईमेल दर्ज करें",
  "emailRequired": "कृपया अपना ईमेल दर्ज करें",
  "invalidEmail": "कृपया एक मान्य ईमेल पता दर्ज करें",
  "subscribing": "सदस्यता ली जा रही है...",
  "subscribedSuccess": "आप सदस्यता ले चुके हैं! 🎉",
  "subscribedDesc": "सदस्यता लेने के लिए धन्यवाद। पुष्टि के लिए अपने इनबॉक्स की जाँच करें।",
  "noSpam": "कोई स्पैम नहीं। कभी भी सदस्यता समाप्त करें।",
  "subscriptionError": "कुछ गलत हो गया। कृपया पुनः प्रयास करें।",
  "weeklyPoems": "साप्ताहिक चुनिंदा कविताएँ",
  "exclusiveContent": "विशेष कवियों से विशेष सामग्री",
  "eventUpdates": "इवेंट और प्रतियोगिता अपडेट",

  // ==================== CTA SECTION ====================
  "ctaBadge": "समुदाय से जुड़ें",
  "ctaTitle": "अपनी साहित्यिक यात्रा शुरू करने के लिए तैयार हैं?",
  "ctaDescription": "हजारों कवियों, लेखकों और साहित्य प्रेमियों से जुड़ें जो पहले से ही हमारे बढ़ते समुदाय का हिस्सा हैं।",
  "ctaJoinNow": "अभी मुफ्त में जुड़ें",
  "ctaJoinDesc": "अपना खाता बनाएं और आज ही खोजना शुरू करें।",
  "members": "सदस्य",
  "trustLoved": "पाठकों द्वारा पसंद",
  "trustLovedDesc": "हजारों कविता प्रेमी",
  "trustCurated": "चुनिंदा सामग्री",
  "trustCuratedDesc": "विशेषज्ञों द्वारा चुनी गई",
  "trustCommunity": "सक्रिय समुदाय",
  "trustCommunityDesc": "साथी पाठकों से जुड़ें",
  "trustGlobal": "वैश्विक पहुंच",
  "trustGlobalDesc": "100+ देशों से पाठक",

  // ==================== LITERARY CATEGORIES ====================
  "literaryCategories": "साहित्यिक श्रेणियाँ",
  "categoriesDesc": "दुनिया भर के साहित्य की विभिन्न विधाओं और रूपों का अन्वेषण करें",
  "viewAllCategories": "सभी श्रेणियाँ देखें",

  // ==================== TEST PAGE ====================
  "testPageDescription": "UI घटकों, थीम और इंटरैक्शन का परीक्षण",
  "buttons": "बटन",
  "clickMe": "मुझे क्लिक करें",
  "error": "त्रुटि",
  "warning": "चेतावनी",
  "info": "जानकारी",
  "simulateLoading": "लोडिंग सिम्युलेट करें",
  "loading": "लोड हो रहा है...",
  "buttonClicks": "बटन क्लिक",
  "formElements": "फॉर्म तत्व",
  "textInput": "टेक्स्ट इनपुट",
  "typeSomething": "कुछ टाइप करें...",
  "inputValue": "इनपुट मान",
  "toggleMe": "मुझे टॉगल करें",
  "dropdown": "ड्रॉपडाउन",
  "option1": "विकल्प 1",
  "option2": "विकल्प 2",
  "option3": "विकल्प 3",
  "selected": "चयनित",
  "rangeSlider": "रेंज स्लाइडर",
  "iconShowcase": "आइकन शोकेस",
  "tabs": "टैब",
  "progressBar": "प्रगति पट्टी",
  "colorPalette": "रंग पैलेट",
  "testPageFooter": "यह UI घटकों और इंटरैक्शन के लिए एक परीक्षण पृष्ठ है",

  // ==================== CONTROLS ====================
  "controls": "नियंत्रण",
  "controlsPreferences": "नियंत्रण और प्राथमिकताएँ",
  "literature": "साहित्य",
  "aiTranslation": "एआई अनुवाद",
  "defaultTheme": "डिफ़ॉल्ट एम्बर",
  "forestTheme": "फ़ॉरेस्ट ग्रीन",
  "lavenderTheme": "लैवेंडर पर्पल",
  "roseTheme": "रोज़ पिंक",
  "sepiaTheme": "सेपिया विंटेज",
  "darkTheme": "डार्क मोड",
  "quickSettings": "त्वरित सेटिंग्स",
  "fullPreferences": "पूरी प्राथमिकताएँ",
  "preferencesSaved": "प्राथमिकताएँ स्थानीय रूप से सहेजी गईं",
  "close": "बंद करें",
  "enableRealTimeTranslation": "रियल-टाइम अनुवाद सक्षम करें",
  "audioPlayback": "ऑडियो प्लेबैक",
  "readPoemsAloud": "कविताओं को ज़ोर से पढ़ें",
  "toggleAiTranslation": "एआई अनुवाद टॉगल करें",
  "toggleAudio": "ऑडियो टॉगल करें",
  "selectUpTo3Languages": "3 भाषाओं तक का चयन करें",
  "selectLiteratureLanguage": "साहित्य भाषा चुनें",
  "searchLanguages": "भाषाएँ खोजें...",
  "showMore": "और दिखाएँ",
  "showLess": "कम दिखाएँ",
  "more": "और",
  "languagesAvailable": "भाषाएँ उपलब्ध",
  "select": "चयन करें",
  "romanzation": "रोमानीकरण",
  "convertScriptToLatin": "लिपि को लैटिन अक्षरों में बदलें",
  "enablesTransliteration": "बेहतर पठनीयता के लिए लिप्यंतरण सक्षम करता है",
  "toggleRomanization": "रोमानीकरण टॉगल करें",
  "maxLanguagesReached": "अधिकतम 3 भाषाएँ चयनित",

  // ==================== GENERAL ====================
  "dashboard": "डैशबोर्ड",
  "logout": "लॉग आउट",
  "toggleDropdown": "ड्रॉपडाउन टॉगल करें",
  "noNavItems": "कोई नेविगेशन आइटम लोड नहीं हुआ",
  "openMenu": "मेनू खोलें",
  "closeMenu": "मेनू बंद करें",
  "explore": "खोजें",
  "footerNote": "दुनिया भर के कविता और साहित्य प्रेमियों के लिए ❤️ के साथ बनाया गया",
};