// src/localization/urdu_localization.js

export const urduLocalization = {
  // ==================== NAVIGATION ====================
  "home": "ہوم",
  "poems": "شعری",
  "prose": "نثر",
  "poets": "شعرا",
  "contributors": "تعاون کنندگان",
  "about": "تعارف",
  "testPage": "ٹیسٹ صفحہ",
  
  // Poems Dropdown
  "allPoems": "تمام شعری",
  "popular": "مقبول",
  "new": "نئے",
  "classics": "کلاسیکی",
  "categories": "اقسام",
  "poemTypes": "شعری اقسام",
  
  // Prose Dropdown
  "allProse": "تمام نثر",
  "shortStories": "افسانے",
  "essays": "مقالے",
  "articles": "مضامین",
  "memoirs": "یاداشتیں",
  "literaryCriticism": "ادبی تنقید",
  
  // Poets Dropdown
  "allPoets": "تمام شعرا",
  "featured": "نمایاں",
  "newPoets": "نئے شعرا",
  "interviews": "انٹرویوز",
  
  // Contributors Dropdown
  "allContributors": "تمام تعاون کنندگان",
  "translators": "مترجمین",
  "scholars": "علماء",
  "editors": "مدیران",
  "commentators": "مفسرین",

  // UI Elements
  "search": "شعری، شعرا تلاش کریں...",
  "signUp": "سائن اپ",
  "login": "لاگ ان",
  "profile": "پروفائل",
  "settings": "ترتیبات",
  "notifications": "اطلاعات",
  "theme": "تھیم",
  "language": "زبان",
  "aiAssistant": "اے آئی اسسٹنٹ",
  "aiTools": "اے آئی ٹولز",
  "poemGenerator": "شعر جنریٹر",
  "rhymeFinder": "قافیہ تلاش کریں",
  "meterAnalyzer": "وزن تجزیہ کار",
  "translationAssistant": "ترجمہ معاون",
  "writingPrompts": "تحریری اشارے",
  "account": "اکاؤنٹ",
  "menu": "مینو",

  // ==================== FOOTER ====================
  "brandDescription": "شاعری، نثر اور ادبی اظہار کی پناہ گاہ۔ مختلف زبانوں اور ثقافتوں سے متنوع آوازوں کو دریافت کریں۔",
  "quickLinks": "فوری لنکس",
  "resources": "وسائل",
  "getInTouch": "رابطہ کریں",
  "subscribe": "سبسکرائب کریں",
  "yourEmail": "آپ کا ای میل",
  "subscribeBtn": "سبسکرائب کریں",
  "allRightsReserved": "جملہ حقوق محفوظ ہیں",
  "privacy": "رازداری",
  "terms": "شرائط",
  "sitemap": "سائٹ کا نقشہ",
  "madeWith": "کے ساتھ بنایا گیا",
  "for": "کے لیے",
  "poetryLovers": "شعری شوقین",
  "backToTop": "اوپر جائیں",

  // Footer Resources
  "writingTips": "تحریر کی تجاویز",
  "poetryGlossary": "شعری لغت",
  "famousPoets": "مشہور شعرا",
  "contests": "مقابلے",
  "workshops": "ورکشاپس",
  "poetryForms": "شعری اشکال",

  // ==================== HERO SLIDER ====================
  "featured": "نمایاں",
  "explorePoems": "شعری دریافت کریں",
  "learnMore": "مزید جانیں",
  "welcome": "پراسنگ میں خوش آمدید",
  "exploreLiteraryWorlds": "ادبی دنیا کی تلاش کریں",
  "featuredPoems": "نمایاں شعری",
  "meetPoets": "شعرا سے ملیں",
  "joinCommunity": "ہماری کمیونٹی میں شامل ہوں",
  "read": "پڑھیں",

  // ==================== HOMEPAGE ====================
  "heroTitle": "شاعری، نثر اور ادبی اظہار کی پناہ گاہ",
  "heroSubtitle": "مختلف زبانوں اور ثقافتوں سے متنوع آوازوں کو دریافت کریں۔",
  "heroCta": "شعری دریافت کریں",
  "heroCta2": "مزید جانیں",
  "featuredPoemsDesc": "مشہور اور ابھرتے ہوئے شعرا کی منتخب کردہ شاعری دریافت کریں۔",
  "featuredPoetsDesc": "دنیا بھر کے شعرا کی زندگی اور کام کو دریافت کریں۔",
  "literaryCriticismDesc": "کلاسیکی کاموں کے تجزیہ اور تشریح میں گہرائی میں جائیں۔",
  "exploreNow": "ابھی دریافت کریں",
  "viewAll": "سب دیکھیں",
  "readers": "قارئین",
  "works": "تصانیف",
  "by": "از",
  "likes": "پسند",
  "of": "میں سے",

  // ==================== POEMS PAGE ====================
  "poemsDescription": "دنیا بھر سے شاعری دریافت کریں",
  "searchPoems": "شعری، شعرا تلاش کریں...",
  "filter": "فلٹر",
  "type": "قسم",
  "allTypes": "تمام اقسام",
  "allLanguages": "تمام زبانیں",
  "sortBy": "ترتیب دیں",
  "newest": "تازہ ترین",
  "oldest": "قدیم ترین",
  "mostLiked": "سب سے زیادہ پسند",
  "mostViewed": "سب سے زیادہ دیکھا گیا",
  "noPoemsFound": "کوئی شعر نہیں ملا",
  "tryDifferentSearch": "اپنی تلاش یا فلٹرز کو ایڈجسٹ کریں",
  "showing": "دکھا رہے ہیں",
  "readMore": "مزید پڑھیں",

  // ==================== PROSE PAGE ====================
  "proseDescription": "مقالے، افسانے، یاداشتیں اور مزید دریافت کریں",
  "searchProse": "نثر، مصنفین تلاش کریں...",
  "category": "زمرہ",
  "allCategories": "تمام زمرے",
  "noProseFound": "کوئی نثر نہیں ملا",
  "proseItems": "نثر کے مضامین",

  // ==================== POETS PAGE ====================
  "poetsDescription": "دنیا بھر کے شعرا کو دریافت کریں اور ان کی تصانیف کو تلاش کریں",
  "searchPoets": "نام، ملک یا طرز سے شعرا تلاش کریں...",
  "country": "ملک",
  "allCountries": "تمام ممالک",
  "era": "دور",
  "allEras": "تمام ادوار",
  "mostPopular": "سب سے زیادہ مقبول",
  "mostFollowers": "سب سے زیادہ پیروکار",
  "mostWorks": "سب سے زیادہ تصانیف",
  "noPoetsFound": "کوئی شاعر نہیں ملا",
  "allRoles": "تمام کردار",

  // ==================== CONTRIBUTORS PAGE ====================
  "contributorsDescription": "ان علماء، مترجمین، مدیران اور مفسرین سے ملیں جو ہماری ادبی کمیونٹی کو مالا مال کرتے ہیں",
  "searchContributors": "نام، کردار یا مہارت سے تلاش کریں...",
  "role": "کردار",
  "noContributorsFound": "کوئی تعاون کنندہ نہیں ملا",

  // ==================== ABOUT PAGE ====================
  "aboutTitle": "ہمارے بارے میں",
  "aboutSubtitle": "شاعری، نثر اور ادبی اظہار کی پناہ گاہ",
  "ourMission": "ہمارا مشن",
  "ourVision": "ہمارا وژن",
  "ourValues": "ہماری اقدار",
  "ourImpact": "ہمارا اثر",
  "ourTeam": "ہماری ٹیم",
  "joinUs": "ہماری کمیونٹی میں شامل ہوں",
  "joinUsDesc": "چاہے آپ شاعر ہوں، مصنف ہوں یا ادب کے شوقین، پراسنگ میں آپ کے لیے جگہ ہے۔",
  "contactUs": "رابطہ کریں",

  // ==================== TESTIMONIALS ====================
  "whatReadersSay": "ہمارے قارئین کیا کہتے ہیں",
  "testimonialsDesc": "ہمارے قارئین، مصنفین اور ادب کے شوقین کی کمیونٹی سے سنیں",

  // ==================== NEWSLETTER ====================
  "subscribeNewsletter": "ہمارے نیوز لیٹر کو سبسکرائب کریں",
  "newsletterDesc": "تازہ ترین شاعری، نثر اور ادبی خبریں اپنے ان باکس میں حاصل کریں",
  "yourName": "آپ کا نام (اختیاری)",
  "enterName": "اپنا نام درج کریں",
  "emailAddress": "ای میل پتہ",
  "enterEmail": "اپنا ای میل درج کریں",
  "emailRequired": "براہ کرم اپنا ای میل درج کریں",
  "invalidEmail": "براہ کرم ایک درست ای میل پتہ درج کریں",
  "subscribing": "سبسکرائب ہو رہا ہے...",
  "subscribedSuccess": "آپ سبسکرائب ہو چکے ہیں! 🎉",
  "subscribedDesc": "سبسکرائب کرنے کے لیے شکریہ۔ تصدیق کے لیے اپنے ان باکس کو چیک کریں۔",
  "noSpam": "کوئی اسپیم نہیں۔ کسی بھی وقت انسبسکرائب کریں۔",
  "subscriptionError": "کچھ غلط ہو گیا۔ براہ کرم دوبارہ کوشش کریں۔",
  "weeklyPoems": "ہفتہ وار منتخب شاعری",
  "exclusiveContent": "نمایاں شعرا سے خصوصی مواد",
  "eventUpdates": "ایونٹ اور مقابلہ اپ ڈیٹس",

  // ==================== CTA SECTION ====================
  "ctaBadge": "کمیونٹی میں شامل ہوں",
  "ctaTitle": "کیا آپ اپنے ادبی سفر کا آغاز کرنے کے لیے تیار ہیں؟",
  "ctaDescription": "ہزاروں شعرا، مصنفین اور ادب کے شوقین سے جڑیں جو پہلے سے ہی ہماری بڑھتی ہوئی کمیونٹی کا حصہ ہیں۔",
  "ctaJoinNow": "ابھی مفت میں شامل ہوں",
  "ctaJoinDesc": "اپنا اکاؤنٹ بنائیں اور آج ہی تلاش شروع کریں۔",
  "members": "اراکین",
  "trustLoved": "قارئین کی پسند",
  "trustLovedDesc": "ہزاروں شاعری کے شوقین",
  "trustCurated": "منتخب مواد",
  "trustCuratedDesc": "ماہرین کی منتخب کردہ",
  "trustCommunity": "فعال کمیونٹی",
  "trustCommunityDesc": "ساتھی قارئین سے جڑیں",
  "trustGlobal": "عالمی رسائی",
  "trustGlobalDesc": "100+ ممالک سے قارئین",

  // ==================== LITERARY CATEGORIES ====================
  "literaryCategories": "ادبی زمرے",
  "categoriesDesc": "دنیا بھر کے ادب کی مختلف اصناف اور اشکال کو دریافت کریں",
  "viewAllCategories": "تمام زمرے دیکھیں",

  // ==================== TEST PAGE ====================
  "testPageDescription": "UI اجزاء، تھیمز اور تعاملات کا ٹیسٹ",
  "buttons": "بٹن",
  "clickMe": "مجھے کلک کریں",
  "error": "خرابی",
  "warning": "انتباہ",
  "info": "معلومات",
  "simulateLoading": "لوڈنگ سمیلیٹ کریں",
  "loading": "لوڈ ہو رہا ہے...",
  "buttonClicks": "بٹن کلک",
  "formElements": "فارم کے اجزاء",
  "textInput": "ٹیکسٹ ان پٹ",
  "typeSomething": "کچھ ٹائپ کریں...",
  "inputValue": "ان پٹ کی قیمت",
  "toggleMe": "مجھے ٹوگل کریں",
  "dropdown": "ڈراپ ڈاؤن",
  "option1": "آپشن 1",
  "option2": "آپشن 2",
  "option3": "آپشن 3",
  "selected": "منتخب",
  "rangeSlider": "رینج سلائیڈر",
  "iconShowcase": "آئیکن شوکیس",
  "tabs": "ٹیبز",
  "progressBar": "پیش رفت بار",
  "colorPalette": "رنگ پیلیٹ",
  "testPageFooter": "یہ UI اجزاء اور تعاملات کے لیے ایک ٹیسٹ صفحہ ہے",

  // ==================== CONTROLS ====================
  "controls": "کنٹرولز",
  "controlsPreferences": "کنٹرولز اور ترجیحات",
  "literature": "ادب",
  "aiTranslation": "اے آئی ترجمہ",
  "defaultTheme": "ڈیفالٹ امبر",
  "forestTheme": "فاریسٹ گرین",
  "lavenderTheme": "لیوینڈر پرپل",
  "roseTheme": "روز پنک",
  "sepiaTheme": "سیپیا ونٹیج",
  "darkTheme": "ڈارک موڈ",
  "quickSettings": "فوری ترتیبات",
  "fullPreferences": "مکمل ترجیحات",
  "preferencesSaved": "ترجیحات مقامی طور پر محفوظ ہیں",
  "close": "بند کریں",
  "enableRealTimeTranslation": "ریئل ٹائم ترجمہ کو فعال کریں",
  "audioPlayback": "آڈیو پلے بیک",
  "readPoemsAloud": "شعری کو بلند آواز سے پڑھیں",
  "toggleAiTranslation": "اے آئی ترجمہ ٹوگل کریں",
  "toggleAudio": "آڈیو ٹوگل کریں",
  "selectUpTo3Languages": "3 زبانوں تک منتخب کریں",
  "selectLiteratureLanguage": "ادبی زبان منتخب کریں",
  "searchLanguages": "زبانیں تلاش کریں...",
  "showMore": "مزید دکھائیں",
  "showLess": "کم دکھائیں",
  "more": "مزید",
  "languagesAvailable": "زبانیں دستیاب ہیں",
  "select": "منتخب کریں",
  "romanzation": "رومنائزیشن",
  "convertScriptToLatin": "رسم الخط کو لاطینی حروف میں تبدیل کریں",
  "enablesTransliteration": "بہتر پڑھنے کی اہلیت کے لیے نقل حرفی کو فعال کرتا ہے",
  "toggleRomanization": "رومنائزیشن ٹوگل کریں",
  "maxLanguagesReached": "زیادہ سے زیادہ 3 زبانیں منتخب",

  // ==================== GENERAL ====================
  "dashboard": "ڈیش بورڈ",
  "logout": "لاگ آؤٹ",
  "toggleDropdown": "ڈراپ ڈاؤن ٹوگل کریں",
  "noNavItems": "کوئی نیویگیشن آئٹم لوڈ نہیں ہوا",
  "openMenu": "مینو کھولیں",
  "closeMenu": "مینو بند کریں",
  "explore": "دریافت کریں",
  "footerNote": "دنیا بھر کے شاعری اور ادب کے شوقین کے لیے ❤️ کے ساتھ بنایا گیا",
};

// Default export for backwards compatibility
export default urduLocalization;